### PR TITLE
Update scripts

### PR DESCRIPTION
**Pull request by HemanthJabalpuri**
May be not needed but useful...

### CODE REVIEW

**Comment by osm0sis** [comment]
I don't think we need any of this, honestly.

I'm sure pwd exists, it's just a built-in.

**Comment by HemanthJabalpuri** [comment]
Ok..
just tried
`type pwd`
got builtin...
Closing this PR..

**Comment by osm0sis** [comment]
Thanks, I'll keep the changes in mind for the future though.

**Comment by HemanthJabalpuri** [comment]
`dir="$(cd "$0"/../; echo "$PWD")";`

Edit:- Above seems not working in bash. Below will work correctly
```
tmpd="$PWD"; [ "$PWD" = "/" ] && tmpd=""
case "$0" in
  /*) scriptdir="$0";;
  *) scriptdir="$tmpd/${0#./}";;
esac
scriptdir="${scriptdir%/*}"
```

**Pull request closed without merging**
